### ISSUE TITLE
ProbabilisticScorer learning-from-probes interface

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1385]
While you can do it already, passing information about a successful probe into `ProbabilisticScorer` is somewhat confusing today - you have to do it by calling the payment-failed method with a bogus scid to "blame". We should just wrap that call in a util function and expose it officially.

cc @jkczyz

**Comment by jkczyz** [comment]
We may want to expand this issue to implement a background prober, which would actively probe paths in `NetworkGraph` with various amounts to learn the liquidity balances. It would need an `EventHandler` that could distinguish its probes from actual payments. In the former case, it would need to call the scorer with a fake failed scid as noted. Otherwise, delegate to the actual event handler.

**Comment by TheBlueMatt** [comment]
Another behavior I'm observing with the new scorer (at least with the settings on latest git) - it sometimes gets really excited when it finds a path that works, and tends to strongly prefer things it is confident will work over things its unsure about. that's probably a great outcome during normal payments, cause it seems to often be correct, but when we build a first-class prober, we should definitely make sure the prober is forced to probe each available channel we have outbound capacity on, instead of getting stuck using one, should be easy to do, though, just filter the `ChannelDetails`s we pass through and walk through them as we probe.
