### ISSUE TITLE
Avoid taking and immediately releasing and re-taking channel_state in claim_funds

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1732]
See https://github.com/lightningdevkit/rust-lightning/pull/1656#discussion_r975168020

**Comment by ViktorTigerstrom** [comment]
I've created a branch that would solve this:
https://github.com/ViktorTigerstrom/rust-lightning/tree/2022-09-avoid-retaking-channel-state

But I'm not 100% if we'd actually like to push this change, as it would only be temporary:
Sadly, the acquiring and retaking of the `channel_state` lock will have to be reintroduced with #1507 unless we also move out the `pending_msg_events` lock already from the `channel_state` as well.
The `pending_msg_events` lock is acquired in `claim_funds_from_hop`, and as we aim to move the lock order of the `channel_state` lock with #1507, we can only temporarily lock the `channel_state` in  `claims_funds` to not violate the lock orders.

I'd suggest that instead of pushing this fix, let's move `claimable_htlcs` to a standalone lock instead? `claimable_htlcs` has no consistency guarantees, so it should be pretty simple.

Perhaps this also show's that we'd like to move the `pending_msg_events` lock either before or with #1507. Am I correct to assume that we'd like to have it per peer in the `per_peer_state` lock?
