### ISSUE TITLE
Make `ProbailisticScorer` half-life more linear

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1752]
We had an issue where a user's scoring parameters were set to strongly prefer one channel, but in practice it never actually had any liquidity. As a result, they ended up in somewhat of a loop - once every $SCORER_HALF_LIFE, they'd suddenly be retrying the channel again, and would have to retry it again each time a lower-value payment came through, until eventually the liquidity bounds would be very low, and then it would sit still for a $SCORER_HALF_LIFE, before the process started anew.

While we don't want to remove the half-life, the fact that the liquidity bounds jump by a rather large amount at each half-life is a problem, causing a number of retries along the given channel until we finally get the bounds low enough to stop using it. Instead, we really need to find a way to make the bounds updates more linear.

Sadly, currently we apply half-lives while doing routing, which limits us to ensuring we're doing very fast things (eg shifting, not multiplying) but if we instead did scorer update passes on a few-minute timer and updating all the bounds as we go, we could drop the during-scoring updates and also be much more linear (and slower).

**Comment by jkczyz** [comment]
To avoid needing a timer, could a combination of bit shifting and bit setting provide a less aggressive decay?

**Comment by jkczyz** [comment]
Thinking about this more, there may be a simple way to introduce quarter-life and eighth-life decays.

**Comment by jkczyz** [comment]
Or maybe 3/4 and 7/8 is more accurate way of saying it. 😛

**Comment by jkczyz** [comment]
Wanted to avoid the timer approach for now as it seems more involved than what time I can dedicate at the moment. Not to mention all the test changes that would be required.

Was hoping there would be some bitwise operations that would be simple to implement. Summing the result of 1 decay and 2 decays gives a rough approximation of a 3/4-life, FWIW. There may be a better approach that is more accurate though...

Otherwise, I guess it would be nice if the scorer could be independent of a timer so it could be used out-of-the-box in any typical setup (e.g., remote router) without additional work.
