### ISSUE TITLE
Consier speeding up `get_secure_random_bytes`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#1958]
We really should swap out for a "real" CSPRNG, not because it'll be more secure, but because it'll be way faster than deriving a new HD key and hashing it. Preferrably something chacha-based given we already have chacha in-tree.

**Comment by danielgranhao** [comment]
I can take this up if no one has started yet. 

I've done an initial experiment, and it seems that using chacha can get the execution time of `get_secure_random_bytes` from ~235 ns down to just ~4 ns. 

Some of the tests broke, but I think it's due to them relying on the values that the original method generated using the same `starting_time_nanos` and `starting_time_secs`. Looking into it.

**Comment by danielgranhao** [comment]
I think I need some help here. I opened a draft PR with the current state of my attempt -> #1974.

One unit test fails because 2 `Outpoints` are equal when they should be different. I'm not sure if this shows a problem with the `get_secure_random_bytes()` method or if it's something that must be changed in the tests. I've already spent some time trying to figure it out but to no avail...

Also, I'm not sure of the safety of the RNG implementation. Some thoughts on that would also be appreciated 🙂
