### ISSUE TITLE
Switch `total_consistency_lock` to a `Send` `RwLock` variant

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2003]
When trying to switch to async background processing/event handling in LDK Node, I stumbled across the fact that tokio won't let me spawn a task for the `process_events_async`, as the we currently try to hold the `total_consistency_lock` over `.await` boundaries: https://github.com/lightningdevkit/rust-lightning/blob/e1208bfd66908818604da97e924899d6843078da/lightning/src/ln/channelmanager.rs#L5242-L5259

This is an issue since `RwLockReadGuard` is not `Send`:
```rust
     = help: within `impl futures::Future<Output = ()>`, the trait `std::marker::Send` is not implemented for `std::sync::RwLockReadGuard<'_, ()>`
note: future is not `Send` as this value is used across an await
    --> /Users/ero/.cargo/git/checkouts/rust-lightning-da94c153801dff32/17eafed/lightning/src/ln/channelmanager.rs:5258:18
     |
5242 |         let _read_guard = self.total_consistency_lock.read().unwrap();
     |             ----------- has type `std::sync::RwLockReadGuard<'_, ()>` which is not `Send`
...
5258 |             handler(event).await;
     |                           ^^^^^^ await occurs here, with `_read_guard` maybe used later
...
5264 |     }
     |     - `_read_guard` is later dropped here
note: required by a bound in `tokio::runtime::Runtime::spawn`
    --> /Users/ero/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/runtime.rs:192:21
     |
192  |         F: Future + Send + 'static,
     |                     ^^^^ required by this bound in `tokio::runtime::Runtime::spawn`
```

In order to fix this, we need to explore options for replacing the `RwLock` of `total_consistency_lock`. One option might be taking a suitable dependency such as `parking_lot`, another approach would be to implement our own `RwLock` variant that meets the requirements.

**Comment by TonyGiorgio** [comment]
+1 for removing `Sync + Send` for the background processor. The other area where we have copy-pasted a file from LDK to remove it is in the lightning-transaction-sync::esplora file: https://github.com/lightningdevkit/rust-lightning/commit/e9fa6ecebe547459bdd4c82085de95cbf03800c7  (I can open up a seperate issue on that if it's preferred.)

Since we're coming from wasm, that's fine for us for now. I believe at one point I tried to do a bunch of `unsafe impl Sync/Send` but was in trait/alias hell so I gave up on that for now.
