### ISSUE TITLE
Implement `FromStr` for `NetAddress`

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#2056]
It would be nice to allow for the parsing of `NetAddress`es from `String`, as it's likely needed by users of `NetAddress`, and currently they'd have to create a newtype to do it.

It's really straightforward as we can lean on `to_socket_addrs` and, in case this fails, on `Hostname::try_from`.

**Comment by jbesraa** [comment]
hey
I can try to implement this

**Comment by jbesraa** [comment]
@tnull how would you identify the input string(to which enum property it should be assigned)?

we can do something like this where key is one of the enum props
```rust
fn from_str(s: &str) -> Result<Self, Self::Err> {
  let key = s.split(":")[0]
  let value = s.split(":")[1]
}
```

we can then use match statement
```rust
match key {
 "ipv4": ...,
 "ipv6": ...,
 "hostname": ...,
}
```

**Comment by ayeankit** [comment]
hey @tnull , I would like to do it. Please assign me this issue.

**Comment by jbesraa** [comment]
yes. I was just waiting for the discussion to come into a conclusion.. can u please review the comment above with the code snippet to validate my thoughts..?

**Comment by jbesraa** [comment]
Hey 
Im planning to work on this on Sunday(March 26th). When is the next release scheduled?

**Comment by jbesraa** [comment]
I created initial commit here https://github.com/jbesraa/rust-lightning/commit/20a2482937a4d383a54566592c99b57cc278adc5 
still wip as I need to figure out the onion part, and I need to add a couple of tests to cover the different scenarios

**Comment by Kixunil** [comment]
IIUC `NetAddress` is the same as [`ln_types::P2PAddress`] which already has `FromStr`. Feel free to copy the code if it's useful!

**Comment by Kixunil** [comment]
WTF, I totally remember mentioning it to you but I can't find the conversation!

It could possibly make sense to collaborate more and I'm totally open to handing over the crate. Regarding integrations, IDK what your policy is, here are some reasons I added them:

* `serde` - obviously it's pretty much the serialization standard in Rust
* `slog` - convenient loggig, has *very* conservative MSRV, it was created and is co-maintained by dpc
* `postgres-type` - I use postgres in multiple projects so it felt nice to add it. I'm not very attached to this one especially given it's not stable
* `parse_arg` - my own lightweight crate with very conservative MSRV, makes integration with `confiure_me` very easy. It didn't change for a while but I do plan some changes and eventually stabilization.
* `bitcoin` - pretty much only conversion between amounts

I would personally at least want to continue supporting `serde` and `parse_arg` since these are "interface types" which humans interact with often and have standardized human-readable representation.

**Comment by Kixunil** [comment]
Don't you find `serde` worth the trouble of maintaining the pin? I personally totally do for my crates. But yeah, I'm also annoyed by this crazy MSRV bumps from various important crates (e.g. `tokio`, `time`, `once_cell`...)

**Comment by Kixunil** [comment]
Indeed, that's why having serde impls (de)serialize as strings is important.

**Comment by Kixunil** [comment]
The problem is that defining custom serialization module and slapping `#[serde(with = "...")]` everywhere is annoying.

**Comment by MaxFangX** [comment]
Just want to +1 @Kixunil above; there should be `serde` impls on the most common "interface" types. I don't use the other frameworks so don't have a strong opinion on those.

> I honestly just kinda hate the "rust ecosystem" and don't like bothering to interact

Even if you personally dislike the Rust ecosystem, the fact that most Rust + Bitcoin ecosystem libraries and most of LDK's downstream Rust users use `serde` should be sufficient to establish that LDK should have opt-in serde support as well. Not integrating with `serde` when most of LDK's downstream Rust users do just ends up wasting their time writing repetitive newtype boilerplate just to get some impls which should have existed in the first place.

A quick list of crates / LDK projects that integrate with serde: `bitcoin`, `secp256k1`, `esplora_client`, `electrum_client`, Sensei, Mutiny, Kuutamolabs, rust-teos, hidden-lightning-network, rust-dlc. The rust-bitcoin libraries, for example, have saved us time because types like `Txid`, `secp256k1::PublicKey`, and `Address` already have everything we need and we can just use them natively.

Here's a list of LDK types we serialize in some way or another which we've already newtyped to get a `serde` impl:
- `Invoice` (with `serde_with`'s `SerializeDisplay`, `DeserializeFromStr` derives)
- `PaymentHash`
- `PaymentPreimage`
- `PaymentSecret`
- `ConfirmationTarget`
- In the past, now removed: `ChannelDetails`, `OutPoint`

Granted, this is a short list, and most LDK types don't need it. The logic-heavy / security-critical types like `ChannelManager` etc should absolutely continue to exclusively use LDK's existing serialization scheme. But a few `serde` impls here and would make LDK more ergonomic.

`serde` support could be added conservatively and grow primarily based on user feedback; just add the feature flag and impl it for a few carefully-chosen types which are fundamental or particularly likely to be exposed to end users, then expand gradually as LDK users open issues or `#[derive(..)]` PRs. MSRV policy could mirror that of the `bitcoin` crate.
