### ISSUE TITLE
Don't discard create _channel if a peer goes away

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2096]
Or if they're not connected. We should just retry for a timer tick and then generate a ChannelFailed. Docs should note that users can always refuse to fund or force close if they don't want a channel, but the peer getting disconnected at an exactly inopportune moment seems not worth failing for.

**Comment by MaxFangX** [comment]
What would the `connect_open_channel` function in `ldk-node` look like after this is implemented? Would it skip the call to `connect_peer_if_necessary` in order to avoid the `do_connect_peer` race? I'm not understanding how making `ChannelManager::create_channel` robust to disconnected peers would make `connect_open_channel` less flaky, since it's the call to `do_connect_peer` that fails, not the call to `create_channel` no?

**Comment by jbesraa** [comment]
im happy to try and do this one. 
not sure though where exactly to start.. is this something should be in `rust-lightning/lightning/src/ln/channelmanager.rs
` ?
