### ISSUE TITLE
Custom Feature Bits

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2131]
Now that we set feature bits based on a message handler call rather than a hard-coded thing, we need to support setting custom feature bits explicitly.

**Comment by jkczyz** [comment]
Looks like we'll need to expose `Features::or` as it would be needed in `lightning-custom-message` crate. Thoughts on exposing it via implementing `core::ops::BitOr`?

**Comment by jkczyz** [comment]
Hmm... so it occurs to me that in `PeerManager::handle_message` we check `InitFeatures::requires_unknown_bits` and error if true. Seems we'll instead need to check against those the features required by the message handlers rather than the ones LDK is aware of. Does that sound right?

Related: currently we can only set an unknown feature via `Features::from_le_bytes`. I assume we don't want to expose our sealed traits. Maybe a method for setting arbitrary feature bits is sufficient?

**Comment by jkczyz** [comment]
So there is an experimental range for message types, but not for features, AFAICT.

Also, I suppose it would be possible to set an unknown feature bit in one context even though it may be known in another, unless we check across all context. Not sure how particular we want to get about this, though.

**Comment by jkczyz** [comment]
> I think we just need to pass feature bits in all the places we check them - mostly invoice deserialization and init/peer connection?

I meant when setting the bit.

**Comment by carlaKC** [comment]
Ran into this https://github.com/lightning/blips/pull/24 working on custom features for [LND](https://github.com/lightningnetwork/lnd/pull/7568), might be useful here if you're allowing folks to set custom invoice feature bits.
