### ISSUE TITLE
`OutboundPayments::abandon_payment` doesn't wait for the payment to fail to generate a PaymentFailed Event

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2152]
See discussion at https://github.com/lightningdevkit/rust-lightning/pull/2142#discussion_r1157852690

**Comment by alecchendev** [comment]
Since this is marked with the upcoming milestone if it's easier for someone else to pick this up feel free to take it from me, otherwise I'll have a PR open tomorrow!

**Comment by alecchendev** [comment]
I noticed in `OutboundPayments::abandon_payment` (and in `abandon_entry`) it only pushes an `Event::PaymentFailed` if `payment.get().remaining_parts() == 0` which from what I understand means there aren't any pending HTLCs. From the other places where `Event::PaymentFailed` is pushed (`fail_htlc` and `check_retry_payments`), it seems like this is mainly what it means for the payment to have failed (given it's either `PendingOutboundPayment::Abandoned` or exhausted the retry strategy) - would this mean the issue is resolved or is there something I'm missing?

(Btw I realized I mispoke in https://github.com/lightningdevkit/rust-lightning/pull/2142#discussion_r1157809646 about `PaymentFailed` being "directly" pushed in `abandon_payment`)
