### ISSUE TITLE
Bump dust exposure threshold so we can send HTLCs

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2261]
Currently our default max dust exposure threshold is quite low (5k sats). For a single payment between that number and the dust threshold we'll refuse to send any HTLCs at all. With today's fee market this causes all payments or HTLC forwards between 5k sats and the dust threshold (often up to 10k-15k sats today) to fail entirely.

This doesn't apply to anchor channels.

**Comment by ariard** [comment]
> Currently our default max dust exposure threshold is quite low (5k sats). For a single payment between that number and the dust threshold we'll refuse to send any HTLCs at all.

Yeah this only apply to legacy channels due to the feerate being encompassed for second-stage transaction, and the HTLC being trimmed if it’s not economically rational. Note, I think we still have a throughput limit on anchor channels for concurrent low-value payments. We might go to discard dust HTLC output from max_accepted_htlc, or another way could be to advocate for a special policy regime in Core and have under-dust outputs allowed under the condition they are immediately spend by a CPFP in the same block (an extension of the ephemeral anchor idea).

**Comment by alecchendev** [comment]
I can open this PR - what's a good number to bump to? Maybe 25k sats?
