### ISSUE TITLE
Print contents of our own channel updates for broadcast in non-gossip logs

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2467]
currently when we send a broadcast update for one of our channels (a pretty important action) we only log `Handling BroadcastChannelUpdate event in peer_handler for scid X`, which is kinda useless, we really want to know more about the update itself (which is only logged at the GOSSIP level). We should include the contents in that log.

**Comment by Sharmalm** [comment]
can i try this issue?

**Comment by Sharmalm** [comment]
I think `channelUpdate` message consists various type of information like signature , chain_hash , short_channel_id , timestamp , message_flags , ..... etc . so we have to add all the information instead of only  short_channel_id.
For this above action, we can replace  `msg.contents.short_channel_id` to `msg.contents`.
