### ISSUE TITLE
Blinded Paths are probe-able

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3117]
See https://github.com/lightningdevkit/rust-lightning/pull/3085#issuecomment-2153519927 We probably need to get this done ASAP in the next release since this will invalidate all existing offers.

**Comment by jkczyz** [comment]
We discussed offline possible including a 16-byte nonce in each `BlindedPath` and using this when deriving `Offer::signing_pubkey`. However, we already include an encrypted nonce in `Offer::metadata`. If we include the same nonce in each `BlindedPath`, we could simply check that this nonce matches the nonce in the metadata (after decrypting it) when handling an `InvoiceRequest`. @TheBlueMatt Is this sufficient?

**Comment by jkczyz** [comment]
Oh, actually the `Nonce` isn't encrypted. I was confusing that with the `PaymentId` in the _payer_ metadata. But we use the nonce when encrypting that.

**Comment by jkczyz** [comment]
I had been thinking if it were encrypted with the `ExpandedKey` then we could check against it... but we'd still need some nonce for doing the actual encryption, so I guess that wouldn't work.

**Comment by jkczyz** [comment]
We use the one in the metadata to verify the offer, and computing it requires knowing all the fields (including the paths) in advance. So we'd need to exclude the paths from verification and only construct them when calling `OfferBuilder::build`, which would entail having the user pass a `MessageRouter` or not expose the builder at all in the `ChannelManager` usage.

Hmm... might also be a problem for offers with no amount and description since no other fields would be set? Though maybe having the unique nonce is sufficient?

There's also the case where no paths are given (i.e., deriving metadata for verification and signing using the node id), so we'd need to conditionally set the metadata then.

**Comment by jkczyz** [comment]
Ah, so IIUC we are essentially doing H(offer || nonce) already:

https://github.com/lightningdevkit/rust-lightning/blob/87fc324c71500f017adf535316465825efe083f1/lightning/src/offers/signer.rs#L174

And deriving the secret after including the offer TLVs in the HMAC:

https://github.com/lightningdevkit/rust-lightning/blob/87fc324c71500f017adf535316465825efe083f1/lightning/src/offers/signer.rs#L112-L117

https://github.com/lightningdevkit/rust-lightning/blob/87fc324c71500f017adf535316465825efe083f1/lightning/src/offers/signer.rs#L198-L200

So we'd simply keep the metadata empty and use the same nonce in the blinded paths. When handling a request, we'd pass the received nonce to `InvoiceRequest::verify` instead of using the now-empty metadata. Do I have that right?
