### ISSUE TITLE
Drop user-provided `payer_id` from `InvoiceRequestBuilder`

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3198]
We shouldn't have supported this to begin with, and we should drop it before people start using it.

**Comment by jkczyz** [comment]
Wouldn't this prevent anyone from using the `offers` module in a standalone way? They'd be required to use `ExpandedKey` and `PaymentId`, which are more `ChannelManager`-specific.

**Comment by jkczyz** [comment]
Was just looking at LNDK's usage. It no longer uses a fixed key to sign in order to fix the caching issue -- the spec was changed to cache based on `payer_metadata` instead of `payer_id`, so that should no longer be an issue anyway. However, LNDK does use derived keys from LND for signing. I'm not sure if this is a hard requirement though (cc: @orbitalturtle). Just want to raise that before going forward with this change.

See https://github.com/lndk-org/lndk/pull/133.

**Comment by orbitalturtle** [comment]
@jkczyz Yeah I'm pretty sure it's not a hard requirement for LNDK so moving in that direction should be fine for us! So if I'm understanding right, in the future we'd want to use `request_invoice_deriving_payer_id` and let LDK derive the payer_id instead of using `request_invoice_deriving_metadata`?

**Comment by jkczyz** [comment]
Yes, and doing so means you would call `build_and_sign` instead of `build` and then `sign` as attempting to use the latter methods will fail to compile.
