### ISSUE TITLE
Change invoice request payer_note argument to an option? 

### ISSUE THREAD

**Issue by orbitalturtle** [lightningdevkit/rust-lightning#3213]
I'm wondering whether it'd be possible to change the payer_note parameter here to an Option<String>
https://docs.rs/lightning/latest/lightning/offers/invoice_request/struct.InvoiceRequestBuilder.html#method.payer_note

The problem we're having in LNDK is we would like to optionally allow a user to add a payer note to their invoice request. If the user doesn't pass in a payer note, for now I've resorted to passing in an empty string, but maybe there's some way to optionally call payer_note on our end that I'm not thinking of...

**Comment by jkczyz** [comment]
In LDK, we also allow the user to optionally set the `payer_note`. Here's how we do it:

https://github.com/lightningdevkit/rust-lightning/blob/50d21b7c08bb600127223d86d391943dbafdacf9/lightning/src/ln/channelmanager.rs#L9013-L9016

**Comment by orbitalturtle** [comment]
@jkczyz Ah I see, thank you. I was getting a move error when I did something similar, but it looks like that's because I wasn't calling "into()" beforehand.

**Comment by jkczyz** [comment]
Hmm... the `into()` there is only needed so we don't need conditional compilation there for bindings support. When compiling with `c_bindings`, `Offer::request_invoice_deriving_payer_id` will return `InvoiceRequestWithDerivedPayerIdBuilder` instead of `InvoiceRequestBuilder<DerivedPayerId, secp256k1::All>`.

https://github.com/lightningdevkit/rust-lightning/blob/50d21b7c08bb600127223d86d391943dbafdacf9/lightning/src/offers/offer.rs#L762-L772

By using `into()` the former will be converted the the latter, which is fine for LDK to use internally. I wouldn't think you would need to call `into()`.

**Comment by jkczyz** [comment]
The mover error sounds like you didn't re-assign the builder. Since `payer_note` moves `self`, using `builder` again later wouldn't compile.

**Comment by orbitalturtle** [comment]
Oops yup you're totally right. Clippy also caught that using into() wasn't necessary. Yup it was because I wasn't properly reassigning builder so it could be used later.
