### ISSUE TITLE
`MonitorUpdatingPersister` apparently reads only no-update monitors when archiving

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#3228]
...it should read with updates!

**Comment by yellowred** [comment]
When a channel is being archived using `MonitorUpdatingPersister` it only [reads](https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/util/persist.rs#L765) channel monitor and not channel monitor updates. This works today because of the external assumptions, ie full channel monitor is persisted on every block and after the channel was closed, but there is no guarantee that some change in the future will not break those assumptions and consequentially `MonitorUpdatingPersister`.
