### ISSUE TITLE
invoice: Getter for fallbacks as Address'es

### ISSUE THREAD

**Issue by sgeisler** [lightningdevkit/rust-lightning#882]
The `fallback()` method returns some custom address payload implementation. A regular `fallback_addresses` or so that is just a `Vec<Address>` would be great.

Or an `Into<Address>` for `Fallback`.

**Comment by futurepaul** [comment]
is there any good way right now to convert a `Fallback` into an `Address`? just ran into this and not sure the best strat.

**Comment by futurepaul** [comment]
I'll make an `Into<Address>` based on this logic:

```rs
    match fallback {
        Fallback::SegWitProgram { version, program } => {
            let version = WitnessVersion::from_u5(version).unwrap();
            let script = Script::new_witness_program(version, program.as_slice());
            Address::from_script(&script, Network::Bitcoin)
        }
        Fallback::PubKeyHash(pkh) => {
            let pkh = PubkeyHash::from_slice(&pkh).unwrap();
            let script = Script::new_p2pkh(&pkh);
            Address::from_script(&script, Network::Bitcoin)
        }
        Fallback::ScriptHash(sh) => {
            let sh = ScriptHash::from_slice(&sh).unwrap();
            let script = Script::new_p2sh(&sh);
            Address::from_script(&script, Network::Bitcoin)
        }
    }
```

**Comment by jkczyz** [comment]
Currently, the builder has a method that takes a `Fallback`, which are then exposed via an accessor returning `Vec<&Fallback>`. So an `Into<Address>` would require a `clone` since `self` is taken by value.

We have a few options that I can imagine:
- use the `Into` approach and live with users needing to `clone`
- hide `Fallback` by having separate builder methods for each variant and have the accessor return `Vec<Address>` like BOLT 12 invoices do
- have an inconsistent interface where the builder remains as it is and the accessor returns `Vec<Address>`
- add an additional accessor that returns `Vec<Address>` similar to `private_route` / `route_hints`, which would essentially hide the clone from the user

I'm sorta leaning towards the last option to avoid too much change in the interface, but I'm open to other options.

**Comment by futurepaul** [comment]
sorry I saw this comment after writing this code so thought I'd throw it up here and if it's helpful can iterate, otherwise feel free to close

**Comment by jkczyz** [comment]
> sorry I saw this comment after writing this code so thought I'd throw it up here and if it's helpful can iterate, otherwise feel free to close

Nah, we'll need that or something like that somewhere, regardless. Just need to figure out which interface.
